spring:
  datasource:
    url: jdbc:mysql://10.11.11.158:3306/bidder?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: bidder
    password: yy7l1J7PE*

  redis:
    host: 10.11.11.158
    port: 6379
    jedis.pool:
      max-idle: 10
      max-active: 100

logging:
  config: classpath:logback-local.xml
  file.path: /tmp/logs/report-data
  level:
    xinmei.report.data: INFO


report-data:
  api-token-update-worker:
    enable: false
  druid:
    user: admin
    password: ME!5Td9vR#G9#i
    url: jdbc:avatica:remote:url=https://druid.ops.olaex.biz/druid/v2/sql/avatica/


