server:
  port: 8085

spring:
  application:
    name: report-data
  profiles:
    active: dev

  # 数据库设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml