package xinmei.report.data.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xinmei.report.data.bean.PartnerInformation;
import xinmei.report.data.bean.PartnerInformationExample;

public interface PartnerInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    long countByExample(PartnerInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int deleteByExample(PartnerInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int insert(PartnerInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int insertSelective(PartnerInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    List<PartnerInformation> selectByExample(PartnerInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    PartnerInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int updateByExampleSelective(@Param("record") PartnerInformation record, @Param("example") PartnerInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int updateByExample(@Param("record") PartnerInformation record, @Param("example") PartnerInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int updateByPrimaryKeySelective(PartnerInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    int updateByPrimaryKey(PartnerInformation record);
}