package xinmei.report.data.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xinmei.report.data.bean.ProviderAgent;
import xinmei.report.data.bean.ProviderAgentExample;

public interface ProviderAgentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    long countByExample(ProviderAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int deleteByExample(ProviderAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int insert(ProviderAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int insertSelective(ProviderAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    List<ProviderAgent> selectByExample(ProviderAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    ProviderAgent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int updateByExampleSelective(@Param("record") ProviderAgent record, @Param("example") ProviderAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int updateByExample(@Param("record") ProviderAgent record, @Param("example") ProviderAgentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int updateByPrimaryKeySelective(ProviderAgent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table provider_agent
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    int updateByPrimaryKey(ProviderAgent record);
}