package xinmei.report.data.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import xinmei.report.data.bean.SpreadSheetTable;
import xinmei.report.data.bean.SpreadSheetTableExample;

public interface SpreadSheetTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    long countByExample(SpreadSheetTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int deleteByExample(SpreadSheetTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int insert(SpreadSheetTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int insertSelective(SpreadSheetTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    List<SpreadSheetTable> selectByExample(SpreadSheetTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    SpreadSheetTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int updateByExampleSelective(@Param("record") SpreadSheetTable record, @Param("example") SpreadSheetTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int updateByExample(@Param("record") SpreadSheetTable record, @Param("example") SpreadSheetTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int updateByPrimaryKeySelective(SpreadSheetTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table spread_sheet_table
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    int updateByPrimaryKey(SpreadSheetTable record);
}