package xinmei.report.data.bean;

import java.util.ArrayList;
import java.util.List;
import xinmei.report.data.enums.RTBType;
import xinmei.report.data.enums.State;
import xinmei.report.data.enums.TimeZone;

public class PartnerInformationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected int limitOffset = -1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected int limitSize = 1;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public PartnerInformationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void setLimitOffset(int limitOffset) {
        this.limitOffset = limitOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public void setLimitSize(int limitSize) {
        this.limitSize = limitSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public int getLimitOffset() {
        return limitOffset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public int getLimitSize() {
        return limitSize;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("`type` is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("`type` is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(RTBType value) {
            addCriterion("`type` =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(RTBType value) {
            addCriterion("`type` <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(RTBType value) {
            addCriterion("`type` >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(RTBType value) {
            addCriterion("`type` >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(RTBType value) {
            addCriterion("`type` <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(RTBType value) {
            addCriterion("`type` <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(RTBType value) {
            addCriterion("`type` like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(RTBType value) {
            addCriterion("`type` not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<RTBType> values) {
            addCriterion("`type` in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<RTBType> values) {
            addCriterion("`type` not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(RTBType value1, RTBType value2) {
            addCriterion("`type` between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(RTBType value1, RTBType value2) {
            addCriterion("`type` not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("`state` is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("`state` is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(State value) {
            addCriterion("`state` =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(State value) {
            addCriterion("`state` <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(State value) {
            addCriterion("`state` >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(State value) {
            addCriterion("`state` >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(State value) {
            addCriterion("`state` <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(State value) {
            addCriterion("`state` <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(State value) {
            addCriterion("`state` like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(State value) {
            addCriterion("`state` not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<State> values) {
            addCriterion("`state` in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<State> values) {
            addCriterion("`state` not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(State value1, State value2) {
            addCriterion("`state` between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(State value1, State value2) {
            addCriterion("`state` not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andUtcIsNull() {
            addCriterion("utc is null");
            return (Criteria) this;
        }

        public Criteria andUtcIsNotNull() {
            addCriterion("utc is not null");
            return (Criteria) this;
        }

        public Criteria andUtcEqualTo(TimeZone value) {
            addCriterion("utc =", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcNotEqualTo(TimeZone value) {
            addCriterion("utc <>", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcGreaterThan(TimeZone value) {
            addCriterion("utc >", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcGreaterThanOrEqualTo(TimeZone value) {
            addCriterion("utc >=", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcLessThan(TimeZone value) {
            addCriterion("utc <", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcLessThanOrEqualTo(TimeZone value) {
            addCriterion("utc <=", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcLike(TimeZone value) {
            addCriterion("utc like", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcNotLike(TimeZone value) {
            addCriterion("utc not like", value, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcIn(List<TimeZone> values) {
            addCriterion("utc in", values, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcNotIn(List<TimeZone> values) {
            addCriterion("utc not in", values, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcBetween(TimeZone value1, TimeZone value2) {
            addCriterion("utc between", value1, value2, "utc");
            return (Criteria) this;
        }

        public Criteria andUtcNotBetween(TimeZone value1, TimeZone value2) {
            addCriterion("utc not between", value1, value2, "utc");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNull() {
            addCriterion("app_key is null");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNotNull() {
            addCriterion("app_key is not null");
            return (Criteria) this;
        }

        public Criteria andAppKeyEqualTo(String value) {
            addCriterion("app_key =", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotEqualTo(String value) {
            addCriterion("app_key <>", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThan(String value) {
            addCriterion("app_key >", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("app_key >=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThan(String value) {
            addCriterion("app_key <", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThanOrEqualTo(String value) {
            addCriterion("app_key <=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLike(String value) {
            addCriterion("app_key like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotLike(String value) {
            addCriterion("app_key not like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyIn(List<String> values) {
            addCriterion("app_key in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotIn(List<String> values) {
            addCriterion("app_key not in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyBetween(String value1, String value2) {
            addCriterion("app_key between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotBetween(String value1, String value2) {
            addCriterion("app_key not between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKey2IsNull() {
            addCriterion("app_key2 is null");
            return (Criteria) this;
        }

        public Criteria andAppKey2IsNotNull() {
            addCriterion("app_key2 is not null");
            return (Criteria) this;
        }

        public Criteria andAppKey2EqualTo(String value) {
            addCriterion("app_key2 =", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2NotEqualTo(String value) {
            addCriterion("app_key2 <>", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2GreaterThan(String value) {
            addCriterion("app_key2 >", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2GreaterThanOrEqualTo(String value) {
            addCriterion("app_key2 >=", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2LessThan(String value) {
            addCriterion("app_key2 <", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2LessThanOrEqualTo(String value) {
            addCriterion("app_key2 <=", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2Like(String value) {
            addCriterion("app_key2 like", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2NotLike(String value) {
            addCriterion("app_key2 not like", value, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2In(List<String> values) {
            addCriterion("app_key2 in", values, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2NotIn(List<String> values) {
            addCriterion("app_key2 not in", values, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2Between(String value1, String value2) {
            addCriterion("app_key2 between", value1, value2, "appKey2");
            return (Criteria) this;
        }

        public Criteria andAppKey2NotBetween(String value1, String value2) {
            addCriterion("app_key2 not between", value1, value2, "appKey2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partner_information
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 29 10:40:43 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table partner_information
     *
     * @mbg.generated Thu Jun 29 10:40:43 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}