package xinmei.report.data.bean;

import xinmei.report.data.enums.State;

public class ProviderAgent {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider_agent.id
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider_agent.name
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider_agent.state
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    private State state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider_agent.id
     *
     * @return the value of provider_agent.id
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider_agent.id
     *
     * @param id the value for provider_agent.id
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider_agent.name
     *
     * @return the value of provider_agent.name
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider_agent.name
     *
     * @param name the value for provider_agent.name
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider_agent.state
     *
     * @return the value of provider_agent.state
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public State getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider_agent.state
     *
     * @param state the value for provider_agent.state
     *
     * @mbg.generated Mon Jun 26 15:40:24 CST 2023
     */
    public void setState(State state) {
        this.state = state;
    }
}