package xinmei.report.data.bean;

public class SpreadSheetTable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_sheet_table.id
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column spread_sheet_table.spreadsheetId
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    private String spreadsheetid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_sheet_table.id
     *
     * @return the value of spread_sheet_table.id
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_sheet_table.id
     *
     * @param id the value for spread_sheet_table.id
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column spread_sheet_table.spreadsheetId
     *
     * @return the value of spread_sheet_table.spreadsheetId
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    public String getSpreadsheetid() {
        return spreadsheetid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column spread_sheet_table.spreadsheetId
     *
     * @param spreadsheetid the value for spread_sheet_table.spreadsheetId
     *
     * @mbg.generated Mon Jun 19 11:09:05 CST 2023
     */
    public void setSpreadsheetid(String spreadsheetid) {
        this.spreadsheetid = spreadsheetid;
    }
}